#requires -Version 5.1
<#
.SYNOPSIS
    Wires the Ultimate PowerShell Profile into every PowerShell window on this PC.

.DESCRIPTION
    In plain English:
        This script tells PowerShell "every time you start, load my profile
        from the dotfiles repo." After running it, every new PowerShell
        window (Console, Windows Terminal, VS Code, ISE) will automatically
        load the profile.

    What it actually does:
        Writes a tiny "stub" file to the AllHosts profile location for both
        PowerShell 7 and Windows PowerShell 5.1. The stub is one line that
        dot-sources the main profile from this repo - so the real code
        stays in the repo and you can `git pull` to update it.

        The AllHosts profile is loaded by every host (Console, Terminal,
        VS Code, ISE), so a single stub covers them all.

    Why per-host profile files get cleaned up:
        Windows also looks for host-specific profiles like
        Microsoft.PowerShell_profile.ps1 in the same folder. Those load
        AFTER AllHosts and would silently override the profile we just
        installed. Unless -KeepHostProfiles is passed, this script backs
        them up to *.bak.<timestamp> and removes them.

    Scope (where the stub is written):
        - User scope is always written (no admin needed).
        - Machine scope ($PSHOME\profile.ps1) is written when running as
          administrator OR when -Machine is passed. Use -NoMachine to skip
          even if elevated.
        - -MachineOnly skips the user-scope writes (handy on shared PCs).

    Editions:
        Targets PowerShell 7 and Windows PowerShell 5.1 by default. Use
        -PS7Only / -PS51Only to narrow. Editions that aren't installed are
        skipped automatically.

.PARAMETER Force
    Overwrite existing AllHosts profiles without making a backup, even if
    they aren't our stub. Use only if you're sure you don't need them.

.PARAMETER Machine
    Write machine-scope profiles (for all users on this PC) even if not
    running elevated. Will fail with "access denied" if not actually admin.

.PARAMETER NoMachine
    Skip machine-scope profiles even when running elevated.

.PARAMETER MachineOnly
    Skip the user-scope writes entirely. Useful for shared machines where
    only the all-users profile should be set up.

.PARAMETER PS7Only
    Only target PowerShell 7 profile locations.

.PARAMETER PS51Only
    Only target Windows PowerShell 5.1 profile locations.

.PARAMETER KeepHostProfiles
    Do not touch any pre-existing per-host profile files. (Without this
    flag, they are backed up and removed so they don't shadow ours.)

.EXAMPLE
    .\install.ps1
    Wire the profile in for the current user only.

.EXAMPLE
    .\install.ps1 -Machine
    Wire it in for ALL users on this PC (must be run as admin).

.EXAMPLE
    .\install.ps1 -PS7Only -KeepHostProfiles
    Only set it up for PowerShell 7 and don't disturb existing host-specific
    profile files.
#>
[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$Machine,
    [switch]$NoMachine,
    [switch]$MachineOnly,
    [switch]$PS7Only,
    [switch]$PS51Only,
    [switch]$KeepHostProfiles
)

$ErrorActionPreference = 'Stop'

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------

$repoRoot     = $PSScriptRoot
$mainProfile  = Join-Path $repoRoot 'Microsoft.PowerShell_profile.ps1'
if (-not (Test-Path $mainProfile)) {
    throw "Main profile not found at $mainProfile"
}

$marker = '# >>> dotfiles-windows profile stub <<<'

# Single-quote the repo path so backslashes need no escaping; the path is
# resolved at install time and baked into the stub.
$stubContent = @"
$marker
# Generated by install.ps1 — do not edit.
# Loads the modular dotfiles profile. Edits to the repo apply on next shell
# start, or run ``reload`` in an existing session.
. '$mainProfile'
"@

function Test-Admin {
    $id = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object System.Security.Principal.WindowsPrincipal($id)
    $p.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Test-IsOurStub {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return $false }
    $first = Get-Content $Path -TotalCount 1 -ErrorAction SilentlyContinue
    return ($first -and $first.Contains($marker))
}

function Backup-IfExists {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return $null }
    $ts  = Get-Date -Format 'yyyyMMdd-HHmmss'
    $bak = "$Path.bak.$ts"
    Copy-Item -Path $Path -Destination $bak -Force
    return $bak
}

function Write-Stub {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][string]$Label)

    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) {
        try { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        catch { Write-Host "  [!] $Label`: cannot create $dir ($($_.Exception.Message))" -ForegroundColor Yellow; return }
    }

    if (Test-IsOurStub -Path $Path) {
        Set-Content -Path $Path -Value $stubContent -Encoding UTF8 -NoNewline
        Write-Host "  [=] $Label`: refreshed $Path" -ForegroundColor DarkGray
        return
    }

    if (Test-Path $Path) {
        if (-not $Force) {
            $bak = Backup-IfExists -Path $Path
            Write-Host "  [+] $Label`: backed up existing -> $bak" -ForegroundColor Yellow
        } else {
            Write-Host "  [!] $Label`: overwriting (no backup, -Force)" -ForegroundColor Yellow
        }
    }

    try {
        Set-Content -Path $Path -Value $stubContent -Encoding UTF8 -NoNewline
        Write-Host "  [✓] $Label`: wrote $Path" -ForegroundColor Green
    } catch {
        Write-Host "  [✗] $Label`: failed — $($_.Exception.Message)" -ForegroundColor Red
    }
}

function Clear-HostOverrides {
    param([Parameter(Mandatory)][string]$Directory, [Parameter(Mandatory)][string]$Label)
    if (-not (Test-Path $Directory)) { return }

    $hostFiles = @(
        'Microsoft.PowerShell_profile.ps1',
        'Microsoft.VSCode_profile.ps1',
        'Microsoft.PowerShellISE_profile.ps1'
    )

    foreach ($name in $hostFiles) {
        $p = Join-Path $Directory $name
        if (-not (Test-Path $p)) { continue }

        if (Test-IsOurStub -Path $p) {
            try {
                Remove-Item $p -Force
                Write-Host "  [-] $Label`: removed stale stub $name" -ForegroundColor DarkGray
            } catch { Write-Host "  [!] $Label`: could not remove $name — $($_.Exception.Message)" -ForegroundColor Yellow }
            continue
        }

        try {
            $bak = Backup-IfExists -Path $p
            Remove-Item $p -Force
            Write-Host "  [+] $Label`: $name shadowed AllHosts — backed up to $bak and removed" -ForegroundColor Yellow
        } catch {
            Write-Host "  [!] $Label`: could not handle $name — $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }
}

# -----------------------------------------------------------------------------
# Build the target list.
# -----------------------------------------------------------------------------

$IsAdmin       = Test-Admin
$wantUser      = -not $MachineOnly
$wantMachine   = ($Machine -or $IsAdmin) -and (-not $NoMachine)

if ($Machine -and -not $IsAdmin) {
    Write-Host '[!] -Machine requested but not running elevated — machine writes will likely fail.' -ForegroundColor Yellow
}

# PS 5.1 machine-scope is well-known.
$ps51UserDir = Join-Path $HOME 'Documents\WindowsPowerShell'
$ps51MachDir = "$env:windir\System32\WindowsPowerShell\v1.0"
$haveP51     = Test-Path $ps51MachDir

# PS 7 PSHOME varies by install source (MSI/winget vs Microsoft Store). Detect
# it by asking pwsh itself. Skip machine-scope if pwsh lives under WindowsApps,
# which is locked down even for admins.
$ps7UserDir = Join-Path $HOME 'Documents\PowerShell'
$ps7MachDir = $null
$haveP7     = $false
$pwshCmd    = Get-Command pwsh -ErrorAction SilentlyContinue
if ($pwshCmd) {
    try {
        $detected = & pwsh -NoProfile -NoLogo -Command '$PSHOME' 2>$null
        if ($detected -and (Test-Path $detected)) {
            $haveP7     = $true
            $ps7MachDir = $detected
            if ($detected -like '*\WindowsApps\*' -and $wantMachine) {
                Write-Host "[!] PS 7 is Microsoft Store-installed ($detected) — machine-scope is read-only for that source." -ForegroundColor Yellow
                Write-Host "    Reinstall PS 7 from MSI/winget (Microsoft.PowerShell) for machine-scope support." -ForegroundColor DarkGray
                $ps7MachDir = $null   # signal: skip PS 7 machine
            }
        }
    } catch {
        Write-Host "[!] Could not probe pwsh PSHOME: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

if ($PS7Only)  { $haveP51 = $false }
if ($PS51Only) { $haveP7  = $false }

if (-not $haveP7 -and -not $haveP51) {
    throw 'No PowerShell editions detected. Check -PS7Only / -PS51Only.'
}

$targets = New-Object System.Collections.Generic.List[object]

if ($haveP7) {
    if ($wantUser) {
        $targets.Add([pscustomobject]@{ Edition='PS7'; Scope='User'; Dir=$ps7UserDir; Path=(Join-Path $ps7UserDir 'profile.ps1') })
    }
    if ($wantMachine -and $ps7MachDir) {
        $targets.Add([pscustomobject]@{ Edition='PS7'; Scope='Machine'; Dir=$ps7MachDir; Path=(Join-Path $ps7MachDir 'profile.ps1') })
    }
}
if ($haveP51) {
    if ($wantUser) {
        $targets.Add([pscustomobject]@{ Edition='PS51'; Scope='User'; Dir=$ps51UserDir; Path=(Join-Path $ps51UserDir 'profile.ps1') })
    }
    if ($wantMachine) {
        $targets.Add([pscustomobject]@{ Edition='PS51'; Scope='Machine'; Dir=$ps51MachDir; Path=(Join-Path $ps51MachDir 'profile.ps1') })
    }
}

# -----------------------------------------------------------------------------
# Apply.
# -----------------------------------------------------------------------------

Write-Host ''
Write-Host "Installing AllHosts profile stubs (admin: $IsAdmin)" -ForegroundColor Cyan
Write-Host "Main profile: $mainProfile" -ForegroundColor DarkGray
Write-Host ''

foreach ($t in $targets) {
    $label = "$($t.Edition)/$($t.Scope)"
    Write-Host "$label  →  $($t.Path)" -ForegroundColor Cyan
    Write-Stub -Path $t.Path -Label $label
    if (-not $KeepHostProfiles) { Clear-HostOverrides -Directory $t.Dir -Label $label }
    Write-Host ''
}

Write-Host 'Done. Open a new shell to load the profile.' -ForegroundColor Green
if (-not $wantMachine -and -not $MachineOnly) {
    Write-Host 'Tip: re-run elevated (or with -Machine) to also install for all users.' -ForegroundColor DarkGray
}
